services:
  security-api:
    build:
      context: .
      dockerfile: "MS.Security.Net9.SecurityAPI/Dockerfile"
    image: ms-security-api:1.0.0
    environment:
      - ASPNETCORE_URLS=http://+:5073
    networks:
      - internal
    container_name: security-api

  currency-market-api:
    build:
      context: .
      dockerfile: "MS.Security.Net9.CurrencyMarketAPI/Dockerfile"
    image: ms-currency-market-api:1.0.0
    environment:
      - ASPNETCORE_URLS=http://+:5054
    networks:
      - internal
    container_name: currency-market-api

  weather-forecast-api:
    build:
      context: .
      dockerfile: "MS.Security.Net9.WeatherForecastAPI/Dockerfile"
    image: ms-weather-forecast-api:1.0.0
    environment:
      - ASPNETCORE_URLS=http://+:5194
    networks:
      - internal
    container_name: weather-forecast-api

  gateway-api:
    build:
      context: .
      dockerfile: "MS.Security.Net9.APIGateway/Dockerfile"
    image: ms-gateway-api:1.0.0
    environment:
      - ASPNETCORE_URLS=http://localhost:5270
    ports:
      - "5270:5270"
    networks:
      - internal
    container_name: gateway-api
    depends_on:
      - weather-forecast-api
      - currency-market-api
      - security-api

  react-front:
    build: 
      context: .
      dockerfile: MS.Security.React.Front/Dockerfile
    image: ms-security-front:1.0.0
    ports:
      - "5173:5173"
    networks:
      - internal
    depends_on:
      - gateway-api
    container_name: react-front

networks:
  internal:
    driver: bridge
