services:
  security-api:
    build:
      context: ./MS.Security.Net9.SecurityAPI
      dockerfile: ./Dockerfile
    image: ms-security-api:dev
    environment:
      - ASPNETCORE_URLS=http://+:5073
    networks:
      - internal
    container_name: security-api

  currency-market-api:
    build:
      context: ./MS.Security.Net9.CurrencyMarketAPI
      dockerfile: ./Dockerfile
    image: ms-currency-market-api:dev
    environment:
      - ASPNETCORE_URLS=http://+:5054
    networks:
      - internal
    container_name: currency-market-api

  weather-forecast-api:
    build:
      context: ./MS.Security.Net9.WeatherForecastAPI
      dockerfile: ./Dockerfile
    image: ms-weather-forecast-api:dev
    environment:
      - ASPNETCORE_URLS=http://+:5194
    networks:
      - internal
    container_name: weather-forecast-api

  gateway-api:
    build:
      context: ./MS.Security.Net9.APIGateway
      dockerfile: Dockerfile
    image: ms-gateway-api:dev
    environment:
      - ASPNETCORE_URLS=http://+:5270
    ports:
      - "5270:5270"
    networks:
      - internal
    container_name: gateway-api

  react-front:
    build: 
      context: ./MS.Security.React.Front
      dockerfile: Dockerfile
    image: ms-security-front:dev
    ports:
      - "5173:5173"
    depends_on:
      - gateway-api
      - weather-forecast-api
      - currency-market-api
      - security-api
    container_name: react-front

networks:
  internal:
    driver: bridge
